### ISSUE TITLE
Invariant Violation: Expected targetIds to be registered

### ISSUE THREAD

**Issue by erakli** [nosferatu500/react-sortable-tree#13]
After recent deps upgrade this error is occurring:

```
Invariant Violation: Expected targetIds to be registered
```

Cause of it is `react-dnd`, the error fires at the first drag, all subsequent drags works as expected.

Code Sandbox: https://codesandbox.io/s/rst-dnd-error-i042r?file=/src/App.js

**Comment by nosferatu500** [comment]
Thanks for reporting this. It's looks like issue inside react-dnd. I will roll back to v14.0.4.

**Comment by nosferatu500** [comment]
Build v4.0.5 will be released in a few hours.

**Comment by cashwanikumar** [comment]
@nosferatu500 

with 14.0.4, it is still same issue, but below version works well

```
    "react-dnd": "13.0.1",
    "react-dnd-html5-backend": "12.1.1",
```
