### ISSUE TITLE
Support adjust virtualized list to make scroll better

### ISSUE THREAD

**Issue by vantoan8x** [nosferatu500/react-sortable-tree#19]
How to adjust virtualized list "reactVirtualizedListProps" -> "overscanRowCount" property to make scroll better instead of blank at top and bottom while scrolling.

Thank

Ref: https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md#prop-types

**Comment by nosferatu500** [comment]
Hi! Can you provide an example with this issue?

I have no any issues with blank spaces during scroll in my project.

**Comment by vantoan8x** [comment]
Dear @nosferatu500,

Example: There is a list of 1000 items,

1. When display, the list only renders N item (mayby 5 items on HTML DOM), example from position index 0 to 4.
2. You can scroll down, or scroll up, it show index from 5 to 9. the HTML DOM only contains 5 items (but index from 5 to 9). there are no any blank item after scroll, but scroll faster, the render seem to be slow at rendering next items and it appear flick a blank gap lightly.

-----------------------------
0
1
2
3
4
-------------------------------
5  => I need 5 to 9 rendered also (it could be named "overscanRowCount" = 5,  number items to be rendered also, 
6        you can know as cached items).
7
8
9
---------------------------

Could you expose react-virtuoso -> overscan ?
ref: https://virtuoso.dev/virtuoso-api-reference/

**Comment by nosferatu500** [comment]
@vantoan8x Hello! Sorry for that delay. I was too busy last week.

Thanks for the link and explanation. I will release a new one build soon.

**Comment by vantoan8x** [comment]
Thank you alot @nosferatu500 !

**Comment by nosferatu500** [comment]
@vantoan8x v4.1.0 has been released. Let me know if everything is ok.

**Comment by vantoan8x** [comment]
After upgrade to 4.1.0, there is a problem to start project
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/953230/160970054-a9ee2ed6-190b-4e48-bc75-ed13efc15876.png">

**Comment by vantoan8x** [comment]
Quote, full text:
ERROR in ./node_modules/@nosferatu500/react-sortable-tree/index.js
Module not found: Error: Can't resolve '@nosferatu500/react-dnd-scrollzone' in '/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-sortable-tree'
resolve '@nosferatu500/react-dnd-scrollzone' in '/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-sortable-tree'
  Parsed request is a module
  using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-sortable-tree/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-sortable-tree/node_modules doesn't exist or is not a directory
      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/node_modules doesn't exist or is not a directory
      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/node_modules doesn't exist or is not a directory
      /Volumes/Data/Gam/Projects/node_modules doesn't exist or is not a directory
      /Volumes/Data/Gam/node_modules doesn't exist or is not a directory
      /Volumes/Data/node_modules doesn't exist or is not a directory
      /Volumes/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules
        using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/package.json (relative path: .)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone is not a file
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone.jsx doesn't exist
            as directory
              existing directory
                use ./index.js from main in package.json
                  using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/package.json (relative path: .)
                    Field 'browser' doesn't contain a valid alias configuration
                    using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/package.json (relative path: ./index.js)
                      no extension
                        Field 'browser' doesn't contain a valid alias configuration
                        /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js doesn't exist
                      .js
                        Field 'browser' doesn't contain a valid alias configuration
                        /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js.js doesn't exist
                      .jsx
                        Field 'browser' doesn't contain a valid alias configuration
                        /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js.jsx doesn't exist
                      as directory
                        /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js doesn't exist
                using path: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index
                  using description file: /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/package.json (relative path: ./index)
                    no extension
                      Field 'browser' doesn't contain a valid alias configuration
                      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index doesn't exist
                    .js
                      Field 'browser' doesn't contain a valid alias configuration
                      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js doesn't exist
                    .jsx
                      Field 'browser' doesn't contain a valid alias configuration
                      /Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.jsx doesn't exist
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-sortable-tree/node_modules]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/node_modules]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/node_modules]
[/Volumes/Data/Gam/Projects/node_modules]
[/Volumes/Data/Gam/node_modules]
[/Volumes/Data/node_modules]
[/Volumes/node_modules]
[/node_modules]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone.js]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone.jsx]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js.js]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.js.jsx]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index]
[/Volumes/Data/Gam/Projects/PMS-WebFront/node_modules/@nosferatu500/react-dnd-scrollzone/index.jsx]
 @ ./node_modules/@nosferatu500/react-sortable-tree/index.js 11:20-65
 @ ./src/framework/pages/Story/Brainstorm/index.jsx
 @ ./src/framework/pages/Story/index.jsx
 @ ./src/framework/routes/index.js
 @ ./src/index.jsx
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./src/index.jsx

**Comment by vantoan8x** [comment]
Dear @nosferatu500,
after install update to 4.1.0 the bug still remianing, let see the video I attached below:

<img width="388" alt="Screen Shot 2022-03-31 at 10 43 05 AM" src="https://user-images.githubusercontent.com/953230/160972065-c9e3dd30-cc71-4d62-8f27-0a3c11c88316.png">



See the Blank screen when I move update and down by touch pad scrolling:

https://user-images.githubusercontent.com/953230/160971932-ab9ea7e2-0eee-4b11-86ea-e368634a313f.mov

v

**Comment by vantoan8x** [comment]
I tried with increaseViewportBy, and overscan, those worked wrong in their document.
ex: https://codesandbox.io/s/esdng?file=/src/App.tsx
I added more lines code:

          overscan={{main: 1000, reverse: 1000}}
          totalCount={1000}
          increaseViewportBy={{top: 200, bottom: 200}}

Still not work:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/953230/161666784-725046ab-5916-4f68-88d0-386619d5f298.png">

**Comment by nosferatu500** [comment]
Well, this happened with React 18. I'm not sure when, but I'll fix it.

**Comment by vantoan8x** [comment]
Thank you alot nosferatu500!

**Comment by vantoan8x** [comment]
Thank you alot @nosferatu500 I wrote new one for me to use!

**Comment by nosferatu500** [comment]
Glad to hear. I also don't plan to work on this fork anymore and have already started working on a completely new solution. Mostly because this package does not meet all the requirements of my current project. It seems to be easier to write your own component than to maintain this one.

**Comment by nosferatu500** [comment]
Glad to hear. I also don't plan to work on this fork anymore and have already started working on a completely new solution. Mostly because this package does not meet all the requirements of my current project. It seems to be easier to write your own component than to maintain this one. @vantoan8x
