### ISSUE TITLE
help offer

### ISSUE THREAD

**Issue by MohammedFaragallah** [nosferatu500/react-sortable-tree#2]
hello @nosferatu500 thank you for working on this 

I would like to help with the migration to typescript, what do you think?

**Comment by nosferatu500** [comment]
Hello @MohammedFaragallah !

Thank you for your offer! 
Honestly, I really don't have time for this right now. I am very busy on another project now and there is no time for this.

It would be great if you could help with this.

I have a lot of other tasks now and I still can't find enough time to migrate existing types to this library. I didn’t think that this could be in great demand, so I did it very slowly. If you can migrate even small part of the code, it will already be a great help. Thanks!

**Comment by nosferatu500** [comment]
Resolved in b65a83b24ae7eb709483b6d8e302a08e632b494f

**Comment by tchesa** [comment]
I got this error when I upgraded `@nosferatu500/react-sortable-tree` to `4.0.0-beta.10` using `react-sortable-tree-theme-minimal` as theme:
```
react-virtuoso: Zero-sized element, this should not happen {child: div}
```
The error disappears if I remove the theme from SortableTree.

**Comment by nosferatu500** [comment]
@tchesa I recommend you to use latest release version v4.0.5

I do not support ```react-sortable-tree-theme-minimal``` but all you need to do it's add height for your row element.
