### ISSUE TITLE
support for react 18

### ISSUE THREAD

**Issue by YiCChi** [nosferatu500/react-sortable-tree#43]
Hello!
Thanks to you I was able to migrate my project from react 16.8 to 17 six months ago.
I want to know if there is any plan for adding support to react 18.
Someone said it can work with react 17/18 In another [https://github.com/nosferatu500/react-sortable-tree/issues/16#issuecomment-1116117759](issue).
Maybe just need to change the peer dependency?..
I can also make a contribution if it's necessary.

**Comment by parsagholipour** [comment]
@YiCChi Which version is installed in `package.lock`. Is it 4.2.0 or above?

**Comment by YiCChi** [comment]
> @YiCChi Which version is installed in `package.lock`. Is it 4.2.0 or above?

It's 4.2.2.

**Comment by parsagholipour** [comment]
@YiCChi It should work. What's the error?

**Comment by YiCChi** [comment]
@parsagholipour 
I'm sorry but in fact there is not an error.
Just a waring from npm about peer dependencies.
So I think maybe we can add react 18 to peer dependencies.

**Comment by parsagholipour** [comment]
@YiCChi You are right. I installed it using `--force` option.

**Comment by nosferatu500** [comment]
Available with v4.3.0

**Comment by YiCChi** [comment]
> Available with v4.3.0

Thank you so much!
