### ISSUE TITLE
`reactVirtualizedListProps` support

### ISSUE THREAD

**Issue by devcer** [nosferatu500/react-sortable-tree#58]
Hi, I see the original library has `reactVirtualizedListProps` support but this fork doesn't have the support yet. Any idea how I could migrate this prop? I think this library works great and I want to help with any write up that might act like a migration guide.

**Comment by nosferatu500** [comment]
The fork uses [react-virtuoso](https://github.com/petyosi/react-virtuoso) instead of [react-virtualized](https://github.com/bvaughn/react-virtualized). Because of this, the fork doesn't have `reactVirtualizedListProps`, but thanks to @rbenton it has `virtuosoProps` instead.
